version: 2
jobs:
    build:
        working_directory: /project/app
        docker:
            - image: circleci/node:7
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: tests
                command: npm test
